version: '3'
services:
  flask:
      image: thiagomachado/huddle-admin:latest
      container_name: flask
      restart: unless-stopped
      ports:
      - '36105:5000'
      env_file:
        - ./.env
      networks:
      - default
      volumes:
        - ./:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - '5432:5432'

volumes:
  db:
    driver: local
  appdata:
    driver: local
