"""empty message

Revision ID: 6c4d8de3b5a5
Revises: 
Create Date: 2022-07-18 07:55:10.689974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4d8de3b5a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_measurement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('humidity', sa.Numeric(), nullable=True),
    sa.Column('sensor_id', sa.BigInteger(), nullable=True),
    sa.Column('time_of_measurement', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_measurement')
    # ### end Alembic commands ###
