"""empty message

Revision ID: b3a2f9642cd8
Revises: 
Create Date: 2022-08-01 17:31:14.635321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a2f9642cd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mac', sa.String(length=256), nullable=True),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_measurement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rfid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deck', sa.String(), nullable=True),
    sa.Column('timeOfMeasurement', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('date_to_complete', sa.DateTime(), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors_material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_measurement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('humidity', sa.Numeric(), nullable=True),
    sa.Column('sensor_id', sa.BigInteger(), nullable=True),
    sa.Column('timeOfMeasurements', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('begin_meassurement_id', sa.BigInteger(), nullable=True),
    sa.Column('end_meassurement_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['begin_meassurement_id'], ['material_measurement.id'], ),
    sa.ForeignKeyConstraint(['end_meassurement_id'], ['material_measurement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_material')
    op.drop_table('material_measurement')
    op.drop_table('sensors_material')
    op.drop_table('task')
    op.drop_table('equipment_measurement')
    op.drop_table('device')
    op.drop_table('alert')
    # ### end Alembic commands ###
