"""empty message

Revision ID: c236aed552c6
Revises: 6c4d8de3b5a5
Create Date: 2022-07-18 12:40:15.770375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c236aed552c6'
down_revision = '6c4d8de3b5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_measurement', sa.Column('timeOfMeasurements', sa.DateTime(), nullable=True))
    op.drop_column('material_measurement', 'time_of_measurement')
    op.drop_column('material_measurement', 'sensor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_measurement', sa.Column('sensor_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('material_measurement', sa.Column('time_of_measurement', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('material_measurement', 'timeOfMeasurements')
    # ### end Alembic commands ###
